# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true

# AndroidX package structure
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true

# Architecture
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# New Architecture
newArchEnabled=true

# Hermes
hermesEnabled=true

# Edge to Edge
edgeToEdgeEnabled=true

# Expo features
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
expo.useLegacyPackaging=false
expo.edgeToEdgeEnabled=true

# Mapbox version
expoRNMapboxMapsVersion=11.0.0

# DO NOT ADD MAPBOX SECRET TOKEN HERE - IT'S IN EAS SECRETS
